#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   goto <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_goto`. Typically I'm using it like:
#
#    goto egn<tab>/fo<tab>
#
# ...to quickly jump into egnwd/foo, for example.
#
# This also accounts for how Go structures its projects. For example, it will
# autocomplete both on $PROJECTS, and also assume you want to autocomplete on
# your Go projects in $GOPATH/src.

cd "$PROJECTS/$1"
