export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH=$PATH:"/usr/local/sicstus4.3.5/bin"
export PATH="/Applications/MATLAB_R2017b.app/bin:$PATH"
export PATH="$HOME/Library/Haskell/bin:$PATH"
export PATH="$HOME/projects/masters-project/ilasp:$PATH"
export PATH="/usr/local/share/dotnet:$PATH"
